version: '3.7'

services:
  minio1:
    image: minio/minio
    volumes:
      - minio1_data:/data
    environment:
      MINIO_ROOT_USER: local_minio
      MINIO_ROOT_PASSWORD: local_minio123
      MINIO_SERVER: http://localhost:9001
    command: server /data
    ports:
      - "9001:9000"

  minio2:
    image: minio/minio
    volumes:
      - minio2_data:/data
    environment:
      MINIO_ROOT_USER: local_minio
      MINIO_ROOT_PASSWORD: local_minio123
      MINIO_SERVER: http://localhost:9002
    command: server /data
    ports:
      - "9002:9000"

  minio3:
    image: minio/minio
    volumes:
      - minio3_data:/data
    environment:
      MINIO_ROOT_USER: local_minio
      MINIO_ROOT_PASSWORD: local_minio123
      MINIO_SERVER: http://localhost:9003
    command: server /data
    ports:
      - "9003:9000"

  minio4:
    image: minio/minio
    volumes:
      - minio4_data:/data
    environment:
      MINIO_ROOT_USER: local_minio
      MINIO_ROOT_PASSWORD: local_minio123
      MINIO_SERVER: http://localhost:9004
    command: server /data
    ports:
      - "9004:9000"

volumes:
  minio1_data:
  minio2_data:
  minio3_data:
  minio4_data: